server:
  port: 8080

spring:
  application:
    name: backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI:}

aws:
  region: ${AWS_REGION:sa-east-1}
  endpoint-override: ${AWS_ENDPOINT_OVERRIDE:}
  dynamodb:
    table-name: ${AWS_DYNAMODB_TABLE_NAME:portal-cliente-dev-main}
  s3:
    attachments-bucket: ${AWS_S3_ATTACHMENTS_BUCKET:portal-cliente-dev-attachments}
  sqs:
    attachments-queue-url: ${AWS_SQS_ATTACHMENTS_QUEUE_URL:}

management:
  endpoints:
    web:
      exposure:
        include: health
